import type { GeneratedEmail, GeneratedSite } from "@/lib/validation/schemas";

/**
 * Built-in encounters for when the AI is unavailable. Fictional brands and
 * domains only. The AI generators replace these with fresh ones every time.
 */

export const FALLBACK_EMAILS: GeneratedEmail[] = [
  {
    fromName: "Northstar Bank Security",
    fromAddress: "alerts@northstar-bank-secure.com",
    replyTo: "verify.team.ns@gmail-support.co",
    subject: "Action required: unusual sign-in detected",
    receivedAt: "Today, 08:52",
    paragraphs: [
      "Dear Customer,",
      "We detected a sign-in to your online banking from a new device. If this wasn't you, your account will be suspended within 24 hours unless you verify your identity.",
      "Please confirm your details here: [link:0]",
      "Northstar Bank Security Team",
    ],
    links: [{ text: "Verify my account", shownUrl: "https://northstarbank.com/verify", actualUrl: "http://northstar-verify-login.info/session" }],
    attachments: [],
    scam: true,
    category: "phishing",
    tells: [
      { where: "sender", text: "alerts@northstar-bank-secure.com", note: "The bank's real domain has no extra words like “-secure”." },
      { where: "reply-to", text: "verify.team.ns@gmail-support.co", note: "Replies would go to a completely different, free-mail lookalike address." },
      { where: "link", text: "Verify my account", note: "The link text says northstarbank.com but really goes to northstar-verify-login.info." },
      { where: "body", text: "suspended within 24 hours", note: "A deadline designed to stop you checking." },
    ],
    explanation: "A generic greeting, a lookalike sender, a mismatched reply-to and a link that goes somewhere else. Open your banking app directly instead.",
    targets: ["urgency", "authority", "fear"],
  },
  {
    fromName: "Harbour Dental",
    fromAddress: "reception@harbourdental.co",
    subject: "Your appointment on Thursday",
    receivedAt: "Yesterday, 17:30",
    paragraphs: [
      "Hi,",
      "This is a reminder of your check-up on Thursday at 14:30 with Dr Sen.",
      "If you need to reschedule, reply to this email or call the practice on the number on our website. You can also manage bookings in your patient portal: [link:0]",
      "See you soon,\nHarbour Dental",
    ],
    links: [{ text: "Patient portal", shownUrl: "https://harbourdental.co/portal", actualUrl: "https://harbourdental.co/portal" }],
    attachments: [],
    scam: false,
    category: "legitimate",
    tells: [
      { where: "sender", text: "reception@harbourdental.co", note: "The sender matches the practice's own domain." },
      { where: "link", text: "Patient portal", note: "The link goes exactly where it says." },
      { where: "body", text: "call the practice on the number on our website", note: "It points you to a number you can find yourself — no pressure." },
    ],
    explanation: "Nothing is asked of you, the link goes where it claims, and it invites you to verify through channels you already know.",
    targets: [],
  },
  {
    fromName: "Payroll — Harrow & Finch",
    fromAddress: "payroll@harrow-finch-hr.com",
    subject: "Updated salary statement — please review attached",
    receivedAt: "Today, 11:07",
    paragraphs: [
      "Hello,",
      "Due to this year's salary revision, please review the attached statement and confirm your bank details before 5pm today so that your pay is not delayed.",
      "The document is protected — enable editing to view it.",
    ],
    links: [],
    attachments: [{ name: "Salary_Revision_2026.docm", size: "84 KB" }],
    scam: true,
    category: "phishing",
    tells: [
      { where: "attachment", text: "Salary_Revision_2026.docm", note: "A .docm file contains macros — “enable editing” would run code on your computer." },
      { where: "sender", text: "payroll@harrow-finch-hr.com", note: "Your company's domain doesn't have “-hr” tacked on." },
      { where: "body", text: "before 5pm today", note: "Payroll never needs your bank details by a same-day deadline." },
    ],
    explanation: "A macro-enabled attachment, a lookalike company domain and a same-day deadline. Check with payroll through your company chat.",
    targets: ["authority", "urgency"],
  },
];

export const FALLBACK_SITES: GeneratedSite[] = [
  {
    kind: "login",
    brand: "Northstar Bank",
    domain: "northstar-bank.account-verify.io",
    https: true,
    domainAgeDays: 3,
    headline: "Sign in to Northstar Online Banking",
    subheadline: "For your security, please verify your identity to restore full access.",
    body: ["Your account has been temporarily limited. Complete verification to avoid permanent suspension."],
    cta: "Verify and sign in",
    formFields: ["Customer ID", "Password", "Card number", "One-time passcode"],
    products: [],
    badges: ["256-bit secure", "Verified by SSL"],
    contact: "support@northstar-bank.account-verify.io",
    footer: "© Northstar Bank. All rights reserved.",
    scam: true,
    category: "phishing site",
    tells: [
      { where: "url", text: "northstar-bank.account-verify.io", note: "The real site would be northstarbank.com — here the brand is only a subdomain of account-verify.io." },
      { where: "age", text: "3", note: "The domain was registered 3 days ago." },
      { where: "form", text: "One-time passcode", note: "No login page asks for your card number and a passcode together." },
      { where: "padlock", text: "https", note: "The padlock only means the connection is encrypted — not that the site is honest." },
    ],
    explanation: "A padlock and a familiar logo, on a brand-new domain that isn't the bank's, asking for everything at once.",
    targets: ["authority", "urgency", "verification-request"],
  },
  {
    kind: "shop",
    brand: "Meridian Home",
    domain: "meridianhome.co",
    https: true,
    domainAgeDays: 3650,
    headline: "Autumn sale — up to 30% off",
    subheadline: "Free delivery on orders over 2,000.",
    body: ["Returns within 30 days. Pay by card or on delivery."],
    cta: "Shop the sale",
    formFields: [],
    products: [
      { name: "Linen throw", price: "1,799", was: "2,399" },
      { name: "Ceramic lamp", price: "3,250", was: "3,900" },
      { name: "Oak side table", price: "6,400" },
    ],
    badges: ["30-day returns"],
    contact: "Customer care: 1800 200 4410 · 12 Park Lane, Kolkata",
    footer: "Meridian Home Pvt Ltd · Company registration and returns policy",
    scam: false,
    category: "legitimate",
    tells: [
      { where: "age", text: "3650", note: "The domain has existed for about ten years." },
      { where: "price", text: "1,799", note: "Discounts are ordinary, not impossible." },
      { where: "contact", text: "12 Park Lane, Kolkata", note: "A real address, phone line and returns policy you can check." },
    ],
    explanation: "An established domain, believable prices, cash-on-delivery and a real address. This one is fine.",
    targets: [],
  },
  {
    kind: "investment",
    brand: "QuantaYield",
    domain: "quantayield-pro.app",
    https: true,
    domainAgeDays: 19,
    headline: "Earn 4% daily with AI trading",
    subheadline: "Join 48,000 members already growing their wealth. Guaranteed returns.",
    body: ["Deposit today and our AI engine trades for you around the clock.", "Offer closes tonight: bonus 50% on first deposit."],
    cta: "Start earning",
    formFields: ["Full name", "Phone", "Deposit amount", "UPI ID"],
    products: [],
    badges: ["Regulated", "AI-powered", "Guaranteed"],
    contact: "Chat with your advisor on WhatsApp",
    footer: "QuantaYield Global Ltd",
    scam: true,
    category: "investment scam",
    tells: [
      { where: "copy", text: "4% daily", note: "4% a day is over 1,000% a year. Nothing legitimate pays that." },
      { where: "badge", text: "Guaranteed", note: "Real investments never guarantee returns." },
      { where: "contact", text: "Chat with your advisor on WhatsApp", note: "No registered address or regulator — only a chat app." },
      { where: "age", text: "19", note: "The domain is less than three weeks old." },
    ],
    explanation: "Impossible returns, a countdown bonus, “guaranteed” and a WhatsApp-only advisor on a brand-new domain.",
    targets: ["urgency", "social-pressure"],
  },
];
